# Site settings
title: Sarbbottam’s weblog
description: Sarbbottam’s weblog on web accessibility, html, css, javascript, front-end techniques and front-end eco system.
email: sarbbottam@gmail.com
baseurl: ""
url: "https://sarbbottam.github.io"
github:
  username:  sarbbottam
twitter:
  username: sarbbottam
author: sarbbottam

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-paginate

# Build settings
markdown: kramdown

sass:
  style: compressed

# Blog Settings
permalink: /blog/:year/:month/:day/:title
paginate_path: /page:num/
paginate: 5