# Site settings
title: sarbbottam.github.io
email: sarbbottam@gmail.com
description: Sarbbottam's weblog
baseurl: ""
url: "https://sarbbottam.github.io/"
twitter_username: sarbbottam
github_username:  sarbbottam

# Build settings
markdown: kramdown
permalink: pretty
