# Site settings
title: Sarbbottam's weblog
description: Sarbbottam's weblog
email: sarbbottam@gmail.com
baseurl: ""
url: "https://sarbbottam.github.io"
github:
  username:  sarbbottam
twitter:
  username: sarbbottam
author: sarbbottam

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag

# Build settings
markdown: kramdown

# Blog Settings
permalink: /blog/:year/:month/:day/:title