# Site settings
title: Sarbbottam’s weblog
description: Sarbbottam’s weblog on web accessibility, html, css, javascript, front-end techniques and front-end eco system.
email: sarbbottam@gmail.com
baseurl: ""
url: "https://sarbbottam.github.io"
github:
  username:  sarbbottam
twitter:
  username: sarbbottam
author: sarbbottam

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title
  projects:

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - octopress-paginate

# Build settings
markdown: kramdown

sass:
  style: compressed

# Blog Settings
paginate_path:
  blog: /blog/page/:num/
  project: /project/page/:num/