# Site settings
title: Sarbbottam's weblog
description: Sarbbottam's weblog
email: sarbbottam@gmail.com
baseurl: ""
url: "https://sarbbottam.github.io/"
twitter_username: sarbbottam
github_username:  sarbbottam

# Build settings
markdown: kramdown
permalink: pretty
