# site
title: Sarbbottam’s weblog
description: Sarbbottam’s weblog on web accessibility, html, css, javascript, front-end techniques and front-end eco system.
email: sarbbottam@gmail.com
baseurl: ""
url: "https://sarbbottam.github.io"
github:
  username:  sarbbottam
twitter:
  username: sarbbottam
author: sarbbottam

# collection
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title
  projects:

# pagination
paginate_path:
  blog: /blog/page/:num/
  project: /project/page/:num/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      image:
        path: /images/sarbbottam.jpeg
        height: 100
        width: 100

# build
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - octopress-paginate
