# Site settings
title: Sarbbottam's
description: Sarbbottam’s digital home. Where he shares his projects, screencasts, write-ups on web accessibility, html, css, javascript, front-end techniques and front-end eco system.
email: sarbbottam@gmail.com
baseurl: ""
url: "https://sarbbottam.github.io"
github:
  username:  sarbbottam
twitter:
  username: sarbbottam
author: sarbbottam

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag

# Build settings
markdown: kramdown

# Blog Settings
permalink: /blog/:year/:month/:day/:title